### ISSUE TITLE
DACA Renewal Visualization

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#27]
The NILC has requested a visualization for the [DACA Renewal Status Data](https://github.com/Data4Democracy/immigration-connect/files/1532918/2017-11-02_DACA_Renewal_Status_With_Denials_rounded_to_nearest_10.pdf) they have provided us.

In particular, they are interested in a visualization of the distinction between those DACA recipients who are able to renew and those who are not. People whose DACA expires before March 5th can still renew, though at the moment they have to do it before the Oct. 5th deadline, whereas people whose DACA expires after March 5th can never renew again.

Please reach out to me in the #immigration-connect channel in Slack or DM me @jtorrez if you have questions. Patrick, our contact at the NILC, is @pato1974 in the Slack channel, you can also contact him directly for more direction.

***UPDATE(12/3/17):***

Please see @pato1974's [comment](https://github.com/Data4Democracy/immigration-connect/issues/27#issuecomment-349405094) for the current ask, delivery of a finished visualization is an urgent need that should be completed ASAP. 

***UPDATE(12/5/17):***

Removed old data pdf and replaced it with most current data, per @pato1974's ok in the Slack channel.

**Comment by aliang5** [comment]
@jtorrez I'd be happy to look into this. I'm new to this community, can you send me an invitation to the slack group? Thanks!

**Comment by jtorrez** [comment]
Hi @aliang5, sent an invite to the email address you have on your Github profile. Let me know if I should send one to a different address! And feel free to get started on the project, just let me know if you have any questions or I can help in any other way!

**Comment by aliang5** [comment]
@jtorrez Thanks Jonathan!

**Comment by hemavakade** [comment]
@jtorrez I would like to look into this. Can you please send me an invite too?

**Comment by jtorrez** [comment]
@hemavakade I don't see an email on your Github profile, feel free to shoot me an email at jonathan.a.torrez@gmail.com and I can get you invited to Slack

Please feel free to get started on the task in the meantime!

**Comment by aminebouzaghrane** [comment]
I would love to give it a shot. I don't necessarily understand the entire dataset. In particular, the No renewal pending category. What does that mean?

**Comment by jtorrez** [comment]
@aminebouzaghrane It means they have applied for renewal and the application is pending. Let me know if you have any other questions, excited to see what you come up with!

**Comment by aminebouzaghrane** [comment]
@jtorrez so what's the difference between the third and second columns? I'm sorry, for some reason I just can't seem to wrap my head around the difference.

**Comment by pato1974** [comment]
DACA is granted for 2-year periods, at the end of which a person can apply to renew their DACA for another 2 years. A person’s DACA comes up for renewal 120 days before its expiration.  With that in mind, this data set pertains to the DACA submissions for renewal. The first column is the number of renewals that have been granted. The second column is renewal applications that are pending approval. And the third column is the number of people who have DACA but who do not have a renewal in process.

Hope that helps!

Patrick

**Comment by VdeGuzman** [comment]
@jtorrez, I'd love to try this one too. Thanks @pato1974 for explaining further.

**Comment by jtorrez** [comment]
@VdeGuzman would love another take on it, go for it! Let me know how I can support you!

**Comment by biskwikman** [comment]
@jtorrez, It looks like plenty of people have offered already, but I'm interested in giving this a shot. Are you still looking for help?

**Comment by jtorrez** [comment]
Thank you to everyone here for contributing to this project, @pato1974 is super busy right now and will be getting around to reviewing these as soon as he is able.

@biskwikman you are more than welcome to take a cut at this if you'd like to, the more potential visualizations we have the more ideas it might spark for everyone.

**Comment by pato1974** [comment]
NILC really needs an animated visualization that shows how with each month/week/day (not sure by week and day is possible, but…),  that people are losing DACA and therefore losing their status and becoming undocumented. This would use the same data posted here in this issue #27. 

Mohamed's viz gave me the idea to have a visual of that data showing people falling from a vibrant color (i.e. good lives) to a greyscale/darkness (i.e. living in the shadows):
https://public.tableau.com/profile/mohamed.amine4520#!/vizhome/DACAVisualization1/Dashboard)

Mohamed’s works with a slider, which would be fine too (allowing people to interact with it) except that it adjusts when you let go and the fields reconfigure to occupy the space, so the contrast between people who will lose DACA and those who have it still is entirely lost - particularly because the way his is now (as squares) doesn’t give you a visual sense of numbers or that we’re talking about people. So I thought it would be good to have an animated one to post online. Several groups have “tickers” that show how many people have lost DACA since Sept. 5th, but this would show how many people are going to lose it over time, in addition to how many have already lost it. And no one else has a visual - just a number i.e. “10,435 people have lost DACA” which is great but doesn’t tell the story as vividly. 

Please contact me @pato1974 on Slack if you're interested. Thank you for all of the amazing work you do!

Patrick

**Comment by geckya** [comment]
Submitted a PR for the latest version of the code to make the plots.  They have been strung together in Gimp to make a gif that's posted on the Slack and awaiting feedback.
