### ISSUE TITLE
Data Collection to Support NILC Tennessee Court Case

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#28]
The NILC has requested we collect data to support a court case they are pursuing in Tennessee. This data collection will need to cover both social media and other, more traditional news sources and will involve both current and historical data collection. If you decide to take on this project, it is very likely your work will be used in preparation for litigating the court case and possibly even included in the submitted evidence to the court; much potential for impact here!

Please read the full
[TN D4D Data Collection Proposal.docx](https://github.com/Data4Democracy/immigration-connect/files/1327421/TN.D4D.Data.Collection.Proposal.docx) prepared by Patrick (@pato1974) O'Shea, our contact at the NILC, for the specifics of this project, including some background on the case. If you have questions, feel free to post them here, in the #immigration-connect channel in the D4D Slack channel, or DM @jtorrez in Slack.

**Comment by brycecf** [comment]
@jtorrez I'd like to work on this! Is there a deadline for it?

**Comment by jtorrez** [comment]
Awesome! I'll go ahead and assign you to it. Thanks for all your hard work @brycecf; really appreciate it. 

Don't hesitate to ask questions here or in Slack, I'll be sure to ping Patrick if you need clarification from him for any issues.

Re: deadline: I was told by Patrick that this "has a long fuse", but I'll lock down with him exactly when the dates he'll need this by are. Don't think there is too much of a rush here though.

**Comment by brycecf** [comment]
@jtorrez Also, I imagine that the data should be handled/documented in a certain way to be usable in legal proceedings.  Could you talk to Patrick about what (if any) requirements they have for that?

**Comment by joshuAnalytics** [comment]
hi I'm new to this site and found this thread in the data collection tasks section - I'd like to help out if I can. I have some experience scraping historic tweets and am interested in web scraping and social APIs. I have access to cloud computing cpu/disk space. I use python 3 and jupyter a lot.

**Comment by jtorrez** [comment]
@joshuAnalytics Great! We would love your help on this. Check out the collection proposal linked in the issue description and let me know if you have any questions

**Comment by joshuAnalytics** [comment]
Thanks, I will take a look at scraping the historic twitter data

**Comment by jtorrez** [comment]
@brycecf are you still planning on taking this on?

**Comment by jtorrez** [comment]
@joshuAnalytics Have you had any luck either?

**Comment by brycecf** [comment]
@jtorrez I was waiting for clarification on the tasking.  If this data set may be evidence in a legal setting, do we know how this data needs to be collected and stored to make it admissible?  I did some Internet searching on this topic, and it looks like courts have rather stringent requirements.

**Comment by pato1974** [comment]
Hi Bryce,

Thank you so much for following up on this project, and sorry again for the delay in getting back. I sent you a message in Slack on Monday addressing this question (included below), but I’ll reiterate here that there are no special measures that you need to take because it’s a legal case. As long as your methodology is consistent and the scrape includes the actors, keywords and sources we outlined, then it there is no extra step to take.  The distinctions will come into play during the phase after this when we have to analyze all of the data and make determinations as to what is relevant or not. But that is our attorneys’ responsibility.  Thanks again for taking this on.  I can’t even tell you how much this is going to help our case!

If you have absolutely any more questions, just let me know!

Best,
Patrick

@brycecf Hi Bryce. My name is Patrick O'Shea at the National Immigration Law Center. @jtorrez had informed me that you have so graciously volunteered to work on collecting some data for us in our case in Tennessee.  I hope the project  proposal was helpful in articulating what we are looking for, but if not, you should definitely get in touch with me with any and all questions you might have. Seriously...don 't hesitate at all.

Along those lines, @jtorrez passed along to me that you had some questions about specific measures to take in collecting data for a legal case. First, I apologize that it took so long to get back about this, but sometimes it's tough to get a straight answer from attorneys :wink:.  Basically, there are no special measures for a legal case. As long as you use the search criteria we laid out and keep the methodology solid, then whatever you produce will be hugely helpful to the case. The point is that we're trying to show racial animus and discriminatory intent in the construction of this law.  So we want to see if there are news articles, statements, tweets and speeches from the principal political players that help us to prove that.


Patrick O’Shea, PhD | Research & Narrative Strategist
National Immigration Law Center1121 14th St. NW, Suite 200 | Washington, DC 20005
desk: 202.384.1276| cell: 202.870.9652 | email: oshea@nilc.org<mailto:oshea@nilc.org>

**Comment by joshuAnalytics** [comment]
@jtorrez my pull request https://github.com/Data4Democracy/immigration-connect/pull/38 is still open, let me know if I have done it wrong.
